defmodule Advent.Year2025.Day07Test do
  use ExUnit.Case

  import Elixir.Advent.Year2025.Day07

  @input ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

  @tag :skip
  test "part1" do
    result = part1(@input)

    assert result == 21
  end

  @tag :skip
  test "part2" do
    result = part2(@input)

    assert result == 40
  end
end
